// Generated by https://quicktype.io

export interface CuotasVencidas {
    usuario:        string;
    nombreusuario:  string;
    numero:         number;
    nombre:         string;
    direccion:      string;
    provincia:      string;
    canton:         string;
    parroquia:      string;
    barrio:         string;
    direccion1:     string;
    latitud:        string;
    longitud:       string;
    coordenadas:    string;
    telefono:       string;
    saldo:          number;
    saldosvencido:  number;
    diasmoraactual: number;
    garantes:       string;
    socios:         number;
    sociosnuevos:   null;
    scartera:       number;
    ncol:           null;
}

