// Generated by https://quicktype.io

export interface IResponse {
  timeStamp?: string;
  message?:   string;
  code?:      number;
  status?:    string;
  data?:      object | string;
  error?:     string;
}
